<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#文本数据处理" data-toc-modified-id="文本数据处理-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>文本数据处理</a></span><ul class="toc-item"><li><span><a href="#str属性" data-toc-modified-id="str属性-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>str属性</a></span><ul class="toc-item"><li><span><a href="#读入数据演示" data-toc-modified-id="读入数据演示-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>读入数据演示</a></span></li></ul></li><li><span><a href="#使用-str-方法将数据字符串向量化映射" data-toc-modified-id="使用-str-方法将数据字符串向量化映射-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>使用 str 方法将数据字符串向量化映射</a></span><ul class="toc-item"><li><span><a href="#和-python-原生字符串区别不大的方法" data-toc-modified-id="和-python-原生字符串区别不大的方法-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>和 python 原生字符串区别不大的方法</a></span></li></ul></li></ul></li><li><span><a href="#wine数据练习题" data-toc-modified-id="wine数据练习题-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>wine数据练习题</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#高级方法" data-toc-modified-id="高级方法-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>高级方法</a></span></li><li><span><a href="#repalce-方法" data-toc-modified-id="repalce-方法-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>repalce 方法</a></span><ul class="toc-item"><li><span><a href="#普通的-pandas-中的-replace" data-toc-modified-id="普通的-pandas-中的-replace-2.0.2.1"><span class="toc-item-num">2.0.2.1&nbsp;&nbsp;</span>普通的 pandas 中的 replace</a></span></li></ul></li><li><span><a href="#其他方法" data-toc-modified-id="其他方法-2.0.3"><span class="toc-item-num">2.0.3&nbsp;&nbsp;</span>其他方法</a></span></li><li><span><a href="#生成哑变量" data-toc-modified-id="生成哑变量-2.0.4"><span class="toc-item-num">2.0.4&nbsp;&nbsp;</span>生成哑变量</a></span></li></ul></li></ul></li></ul></div>

# 文本数据处理

这一节我们来看一看如何处理 Pandas 中的文本（字符串）。

In [1]:
# 导入相关库
import numpy as np
import pandas as pd

## str属性

Series中可以字符串相关的方法,封装在str子模块下面

### 读入数据演示

In [2]:
grade = pd.read_csv("student_grade_empty.txt",sep='\t')

In [4]:
grade.姓名

0      杨璐
1      王雪
2     韩林霖
3     沙龙逸
4     李鉴学
     ...
63     赵森
64    满朝升
65    李忠浩
66    侯禹志
67    尹鸿涛
Name: 姓名, Length: 68, dtype: object

In [7]:
wine = pd.read_csv("wine.csv",sep=',')

In [8]:
wine.head()

,ID,商品名称,价格（元）,近30天销量（件）,广告词,促销活动,评论数,日期,品牌
0,560796460750,红星二锅头酒白扁56度100ml瓶装清香型白酒小扁二,12.0,961,NaN,NaN,402,2018/2/27,红星
1,45870740587,致中和 韧劲酒香 35度低度小酒125ml 酒厂直供,12.6,115,致中和,满2件7.5折,1750,2018/2/27,致中和
2,43211682074,红星二锅头酒大二绿瓶56度 500ml清香型白酒酒厂直供,13.0,8703,整箱原厂包装 见详情链接,满99元减10元,22575,2018/2/27,红星
3,43261836143,42度牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒,13.0,12722,正宗牛栏山 地道北京味,NaN,18083,2018/2/27,牛栏山
4,540741239830,致中和35度小百年白酒125ml/瓶 建德特产 酒厂直供,15.0,28,NaN,NaN,3103,2018/2/27,致中和

In [9]:
imdb = pd.read_csv('imdb_1000.csv')

In [22]:
imdb.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [23]:
grade.姓名.str.replace('韩' , '书')

0      杨璐
1      王雪
2     书林霖
3     沙龙逸
4     李鉴学
     ...
63     赵森
64    满朝升
65    李忠浩
66    侯禹志
67    尹鸿涛
Name: 姓名, Length: 68, dtype: object

In [24]:
grade['姓名长度'] = grade.姓名.str.len()

In [25]:
grade.姓名长度.value_counts()

3.0    49
2.0    15
4.0     2
Name: 姓名长度, dtype: int64

In [26]:
grade[  grade.姓名长度 == 4 ]

      姓名     语文     数学     英语     总分   班名次  姓名长度
22  张馨月大  114.0  124.0  122.0  360.0  23.0   4.0
36  张馨月小  108.0  110.0  119.0  337.0  37.0   4.0

### 和 python 原生字符串区别不大的方法

1. len
2. lower
3. upper
4. islower
5. isupper
6. find
7. count
8. strip
9. split

# wine数据练习题

wine

1. 把品牌中的红,替换成黑
2. 统计商品名称中"酒" 这个字都出现了多少次,并统计各次数出现的值
3. 提取出日期中的年,月,日 并拆分成三列
4. 提取出天猫超市卖的酒
5. 提取出所有郎酒
6. 提取出所有二锅头

In [14]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 9 columns):
ID           882 non-null int64
商品名称         882 non-null object
价格（元）        881 non-null float64
近30天销量（件）    882 non-null int64
广告词          594 non-null object
促销活动         386 non-null object
评论数          882 non-null int64
日期           882 non-null object
品牌           882 non-null object
dtypes: float64(1), int64(3), object(5)
memory usage: 62.1+ KB

In [15]:
wine.head()

,ID,商品名称,价格（元）,近30天销量（件）,广告词,促销活动,评论数,日期,品牌
0,560796460750,红星二锅头酒白扁56度100ml瓶装清香型白酒小扁二,12.0,961,NaN,NaN,402,2018/2/27,红星
1,45870740587,致中和 韧劲酒香 35度低度小酒125ml 酒厂直供,12.6,115,致中和,满2件7.5折,1750,2018/2/27,致中和
2,43211682074,红星二锅头酒大二绿瓶56度 500ml清香型白酒酒厂直供,13.0,8703,整箱原厂包装 见详情链接,满99元减10元,22575,2018/2/27,红星
3,43261836143,42度牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒,13.0,12722,正宗牛栏山 地道北京味,NaN,18083,2018/2/27,牛栏山
4,540741239830,致中和35度小百年白酒125ml/瓶 建德特产 酒厂直供,15.0,28,NaN,NaN,3103,2018/2/27,致中和

### 高级方法

1. contains 包含 : 判断字符串中是否包含某个自字符
2. startswith :判断是否以子串开始
3. endswith : 判断是否以子串结束

In [53]:
# 提取出姓名中包含杨的数据
grade[grade.姓名.str.contains('杨')]

     姓名   语文   数学   英语   总分  班名次  姓名长度
0    杨璐  131  143  144  418    1     2
29  杨加晖  110  102  136  348   30     3

In [58]:
grade[grade.姓名.str.startswith('杨')]

     姓名   语文   数学   英语   总分  班名次  姓名长度
0    杨璐  131  143  144  418    1     2
29  杨加晖  110  102  136  348   30     3

In [55]:
imdb[imdb.title.str.contains("God")]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
328,8.0,"Aguirre, the Wrath of God",NOT RATED,Adventure,93,"[u'Klaus Kinski', u'Ruy Guerra', u'Helena Rojo']"
711,7.6,The Godfather: Part III,R,Crime,162,"[u'Al Pacino', u'Diane Keaton', u'Andy Garcia']"

In [115]:
grade.姓名.str.contains('刘')

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57     True
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67    False
Name: 姓名, Length: 68, dtype: bool

In [116]:
grade[grade.姓名.str.contains('刘')]

     姓名   语文   数学   英语   总分  班名次  姓名长度
6    刘帅  116  143  140  399    7     2
8   刘钰婷  115  139  135  389    9     3
19   刘姗  124  128  122  374   20     2
57  刘旭辉   99   87   44  230   58     3

In [117]:
grade[grade.姓名.str.contains('林')]

    姓名   语文   数学   英语   总分  班名次  姓名长度
2  韩林霖  127  139  142  408    3     3
9  林世博  116  142  129  387   10     3

In [118]:
grade[grade.姓名.str.startswith('林')]

    姓名   语文   数学   英语   总分  班名次  姓名长度
9  林世博  116  142  129  387   10     3

In [119]:
grade

      姓名   语文   数学   英语   总分  班名次  姓名长度
0     杨璐  131  143  144  418    1     2
1     王雪  131  135  144  410    2     2
2    韩林霖  127  139  142  408    3     3
3    沙龙逸  123  148  136  407    4     3
4    李鉴学  126  135  140  401    5     3
5    韩雨萌  129  133  138  400    6     3
6     刘帅  116  143  140  399    7     2
7    康惠雯  114  142  139  395    8     3
8    刘钰婷  115  139  135  389    9     3
9    林世博  116  142  129  387   10     3
10    张希  123  130  134  387   11     2
11    徐冲  122  124  139  385   12     2
12   苑宇飞  118  136  131  385   13     3
13   卢一凡  121  123  139  383   14     3
14   张瑞鑫  126  115  139  380   15     3
15   范作鑫  121  127  131  379   16     3
16   裴子翔  111  139  128  378   17     3
17   武传禹  119  129  130  378   18     3
18   任雪桐  124  108  144  376   19     3
19    刘姗  124  128  122  374   20     2
20   王柏坤  121  123  128  372   21     3
21   赵永刚  116  131  122  369   22     3
22  张馨月大  114  124  122  360   23     4
23   张曦月  116  123  119  358   24     3
24   胡丁文  116  122  118  356   25     3
25   赵美欣  118  126  111  355   26     3
26   赵殿宇  112  109  130  351   27     3
27   张智文  109  116  125  350   28     3
28    李季  114  117  118  349   29     2
29   杨加晖  110  102  136  348   30     3
..   ...  ...  ...  ...  ...  ...   ...
38    艾宇  115  111  106  332   39     2
39   黄俊焯  101  112  106  319   40     3
40   邹建志   98  104  116  318   41     3
41   张俊奎  103  103  111  317   42     3
42    孙波   96  130   89  315   43     2
43    张良  105  102  105  312   44     2
44   王春月  118   82  112  312   45     3
45   代明哲  101   91  115  307   46     3
46   张开羽  112   90  104  306   47     3
47   狄建译  109   68  126  303   48     3
48   张家硕  107   67  129  303   49     3
49    郭娜   94   98  104  296   50     2
50    周坤  107   76  104  287   51     2
51    洪禹  106  100   80  286   52     2
52   王治超  105   95   82  282   53     3
53   臧云飞  101   59  108  268   54     3
54   袁茂哲   85   95   85  265   55     3
55   丁婉艺   95   71   85  251   56     3
56   于娇莹   97   76   71  244   57     3
57   刘旭辉   99   87   44  230   58     3
58   张宇婷   83   61   71  215   59     3
59   黄明涛   87   77   43  207   60     3
60   吕文卓   82   53   62  197   61     3
61   王晟煜   79   49   64  192   62     3
62   孙龙基   99   21   67  187   63     3
63    赵森   90   29   64  183   64     2
64   满朝升   78   45   47  170   65     3
65   李忠浩   86   32   46  164   66     3
66   侯禹志   75   23   34  132   67     3
67   尹鸿涛   66   23   34  123   68     3

[68 rows x 7 columns]

In [59]:
grade[grade.姓名.str.endswith('月')]

     姓名   语文   数学   英语   总分  班名次  姓名长度
23  张曦月  116  123  119  358   24     3
44  王春月  118   82  112  312   45     3

In [61]:
wine

,ID,商品名称,价格（元）,近30天销量（件）,广告词,促销活动,评论数,日期,品牌
0,560796460750,红星二锅头酒白扁56度100ml瓶装清香型白酒小扁二,12.0,961,NaN,NaN,402,2018/2/27,红星
1,45870740587,致中和 韧劲酒香 35度低度小酒125ml 酒厂直供,12.6,115,致中和,满2件7.5折,1750,2018/2/27,致中和
2,43211682074,红星二锅头酒大二绿瓶56度 500ml清香型白酒酒厂直供,13.0,8703,整箱原厂包装 见详情链接,满99元减10元,22575,2018/2/27,红星
3,43261836143,42度牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒,13.0,12722,正宗牛栏山 地道北京味,NaN,18083,2018/2/27,牛栏山
4,540741239830,致中和35度小百年白酒125ml/瓶 建德特产 酒厂直供,15.0,28,NaN,NaN,3103,2018/2/27,致中和
5,44646135143,四特酒莲四系列莲四52度 500ml特香型白酒江西名酒酒厂直供,16.0,203,特香典范 中国四特 猫超自营 百城次日达,NaN,2469,2018/2/27,四特
6,533909289770,汾酒 山西杏花村竹叶青酒38度玻竹150ml清香型酒,17.5,143,竹叶青 露酒,NaN,1133,2018/2/27,汾酒
7,542806723433,泸州老窖泸小二 42度 125ml 中度 白酒,18.0,79,NaN,NaN,941,2018/2/27,泸州老窖
8,525051924381,洋河 绿敦煌大曲 42度500ml 浓香型白酒 猫超自营,19.0,1187,敦煌大曲 老牌名酒,NaN,2404,2018/2/27,洋河
9,533767751992,牛栏山42度塑桶二锅头2L 清香型桶装白酒特价大牛桶,19.9,2029,正宗牛栏山 地道北京味,NaN,7060,2018/2/27,牛栏山
10,538705671233,安达情闷倒驴60度圆钢壶750ml单瓶装清香型白酒,19.9,218,纯粮高度酒 好喝不上头,NaN,364,2018/2/27,安达情
11,540011154689,泸州老窖 泸州原浆柔和 52度 500mL 白酒浓香型,20.0,3116,NaN,NaN,25921,2018/2/27,泸州老窖
12,523751557195,红星二锅头大二56度 750ml酒厂直供包装更新中,20.0,763,老百姓爱喝的二锅头 天猫自营 百城次日达,满99元减10元,2253,2018/2/27,红星
13,551838729137,【天猫超市】双沟青优42度200ml猫超新品小酒超值优惠酒厂直供,20.0,49,NaN,NaN,325,2018/2/27,双沟
14,562468261759,劲牌劲酒公司和露酒玫瑰花香型8度275mL单瓶装,20.0,89,NaN,NaN,17,2018/2/27,劲牌
15,562989357827,牛栏山52度珍品陈酿（银牛）150ml浓香型小瓶白酒,24.0,4,NaN,NaN,0,2018/2/27,牛栏山
16,523749894366,红星二锅头酒绵柔8陈酿蓝瓶43度500ml白酒酒厂直供,27.0,1677,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,3074,2018/2/27,红星
17,556738841682,牛栏山42度2L桶装二锅头+精武鸭锁骨150g组合装,27.9,30,NaN,NaN,76,2018/2/27,牛栏山
18,537013830676,江小白品鉴酒更多优惠请见详情页非卖品请勿下单！,29.0,121,单纯高粱酿造 精制包装 特色语录,NaN,67514,2018/2/27,江小白
19,521044476993,致中和果酒 青梅酒10度白酒200ml/瓶聚会女生用酒,29.0,415,整箱更优惠,满2件7.5折,10230,2018/2/27,致中和
20,45809251206,致中和白酒莲子酒42度125ml/瓶建德特产酒厂直供,29.0,27,本土红莲酿造 口感清雅醇香,满2件7.5折,4066,2018/2/27,致中和
21,552360897943,古井特曲50度500ml浓香白酒古井贡酒股份平价酒,29.0,71,古井特曲,满99元减30元,1827,2018/2/27,古井贡酒
22,530440341343,牛栏山二锅头白酒 出口美国型56度750ml 清香型白酒,29.9,215,正宗牛栏山 地道北京味 正品特惠,NaN,850,2018/2/27,牛栏山
23,35263656074,红星二锅头酒苏扁50度 500ml清香型白酒酒厂直供,34.0,348,老百姓爱喝的二锅头 天猫自营 百城次日达,满99元减10元,693,2018/2/27,红星
24,541217125531,劲牌劲酒公司露酒32度追风活力500ml 瓶装 白酒,35.0,955,品味美酒,满2件5折,2473,2018/2/27,劲酒
25,523751413489,红星二锅头酒绵柔8陈酿蓝瓶43度 750ml白酒酒厂直供,37.0,1252,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,4962,2018/2/27,红星
26,533909513991,汾酒 山西杏花村竹叶青酒38度玻竹475ml清香型酒,37.9,535,竹叶青 露酒,NaN,2874,2018/2/27,汾酒
27,533859373238,牛栏山珍品陈酿52度(金牛)500ml浓香型新品金牛,38.0,66,正宗牛栏山 地道北京味,NaN,347,2018/2/27,牛栏山
28,523726503584,红星二锅头酒绵柔8陈酿53度 750ml白酒酒厂直供,38.9,1085,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,5856,2018/2/27,红星
29,533832146187,牛栏山(金牛)珍品陈酿39度500ml浓香型 珍品金牛,39.0,116,正宗牛栏山 地道北京味,NaN,806,2018/2/27,牛栏山
...,...,...,...,...,...,...,...,...,...
852,536493211279,水井坊臻酿八号6瓶装52度500ml*6整箱装浓香型白酒,2129.0,209,天猫自营百城次日达 正品保障 品质无忧,NaN,350,2018/2/27,水井坊
853,40556587702,郎酒 红花郎十 53度500mlx6瓶 酱香型 整箱 白酒,2148.0,21,原箱发货（内含礼袋),NaN,196,2018/2/27,郎酒
854,39256922715,52度洋河天之蓝 480ml*6瓶 绵柔型白酒 猫超配送,2178.0,161,不参与天猫超市任何优惠券活动,NaN,516,2018/2/27,洋河
855,543899438700,郎酒青花郎20年53度500ml×2瓶酱香型白酒双支礼袋装,2196.0,110,NaN,NaN,220,2018/2/27,郎酒
856,561267590798,52度洋河天之蓝520ml*6 绵柔型白酒 猫超新品 酒厂直供,2208.0,69,NaN,NaN,22,2018/2/27,洋河
857,553826161701,郎酒红花郎十 53度558mlx6瓶 酱香型高度白酒整箱,2258.0,43,整箱装 内含礼袋,NaN,66,2018/2/27,郎酒
858,555705473809,习酒窖藏1988雅致版53度500ml*4整箱装酱香型白酒,2272.0,66,NaN,满1件送任意1件赠品（赠完即止）,67,2018/2/27,习酒
859,537385391122,牛栏山经典二锅头52度500ml*6整箱装清香型白酒,2288.0,23,正宗牛栏山 地道北京味 箱内礼袋3支,NaN,15,2018/2/27,牛栏山
860,538022692116,白云边20年陈酿粮食酒42度白酒500mL*6瓶整箱特价,2328.0,27,湖北名酒 品牌名酒 纯粮发酵 精细制曲,NaN,26,2018/2/27,白云边
861,540450214555,汾酒杏花村42度青花20清香型白酒500ml*6酒厂直供,2328.0,4,官方授权 天猫配送 保真快捷,NaN,17,2018/2/27,汾酒
862,532583189339,52度剑南春白酒500ml*6整箱酒厂直供不参加任何活动,2388.0,422,不参与天猫超市任何优惠券活动,NaN,788,2018/2/27,剑南春
863,530899370324,茅台赖茅传承-蓝酱香型白酒53度500ml*6酒厂直供,2390.0,60,赖茅不赖 酱香型酒,满2000元减600元；满4000元减1376元,311,2018/2/27,茅台
864,526117179063,汾酒杏花村53度汾酒青花20清香型白酒500ml*6瓶整箱,2448.0,54,官方授权 天猫配送 保真快捷,NaN,107,2018/2/27,汾酒
865,538317516423,五粮液股份52度尊耀珍酿级500ml*30瓶浓香型白酒,2495.0,3,酒味醇厚甘美，喷香浓郁,满999元减150元,21,2018/2/27,五粮液
866,561462254223,茅台赖茅珍品53度500ml*6瓶酱香型白酒酒厂直供,2760.0,37,赖茅珍品，酒厂直供,满1000元减200元,10,2018/2/27,赖茅
867,555779615538,45度洋河梦之蓝M6- 500ml*4 绵柔型白酒 猫超配送 酒厂直供,2796.0,29,NaN,NaN,13,2018/2/27,洋河
868,548477375633,水井坊井台装38度 500ml*6白酒整箱浓香礼盒酒厂直供,2849.0,2,天猫超市自营 百城次日达 品质保证,NaN,5,2018/2/27,水井坊
869,555781135649,52度洋河梦之蓝M6-52度500ml*4 绵柔型白酒 酒厂直供,2912.0,73,NaN,NaN,42,2018/2/27,洋河
870,553612984990,剑南春52度珍藏级天益老号浓香型白酒500ml*6原箱装,2988.0,21,不参与天猫超市任何优惠券活动,NaN,18,2018/2/27,剑南春
871,523188746217,飞天茅台现货53度酱香白酒500ml*2非整箱发货限购1组,2998.0,21685,不参与天猫超市任何优惠券活动,NaN,17980,2018/2/27,茅台
872,537910992262,水井坊井台52度浓香型500mlX6瓶白酒礼盒装酒厂直供,3089.0,29,天猫自营百城次日达 正品保障 品质无忧,NaN,85,2018/2/27,水井坊
873,555744106584,【天猫超市】泸州老窖国窖1573手工版53度 500mLX4整箱浓香型白酒,3240.0,3,NaN,NaN,5,2018/2/27,泸州老窖
874,543781878245,郎酒红花郎15年53度500ml *6瓶酱香白酒酒厂直供,3388.0,77,NaN,满1件送任意1件赠品（赠完即止）,133,2018/2/27,郎酒
875,561459170962,茅台赖茅珍藏53度500ml*6瓶酱香型国产白酒酒厂直供,3399.0,30,NaN,满1000元减200元,21,2018/2/27,赖茅
876,540443712492,汾酒杏花村53度青花30清香型500ml*6整箱酒厂直供,3988.0,31,官方授权 天猫配送 保真快捷,NaN,42,2018/2/27,汾酒
877,521600593441,泸州老窖国窖1573白酒 52度500ml*6瓶整箱装礼品装酒厂直供,5240.0,53,领劵立减200元，好酒不打烊,满1件送任意2件赠品（赠完即止）,153,2018/2/27,泸州老窖
878,538282333692,52度五粮液普五500ml*6猫超自采不参加任何活动,5599.0,473,不参与天猫超市任何优惠券活动,NaN,614,2018/2/27,五粮液
879,540103784273,白酒五粮液1618陶瓷瓶500ml*6原箱装酒水名酒礼盒,5639.0,35,NaN,NaN,61,2018/2/27,五粮液
880,543796215762,郎酒青花郎20年53度500ml*6瓶酱香白酒酒厂直供,6588.0,57,NaN,满1件送任意1件赠品（赠完即止）,114,2018/2/27,郎酒
881,522004673739,五粮液普五52度 500ml*2礼盒装猫超直采高度白酒,NaN,1292,不参与天猫超市任何优惠券活动,满2198元减200元,1319,2018/2/27,五粮液

### repalce 方法

In [123]:
wine

,ID,商品名称,价格（元）,近30天销量（件）,广告词,促销活动,评论数,日期,品牌
0,560796460750,红星二锅头酒白扁56度100ml瓶装清香型白酒小扁二,12.0,961,NaN,NaN,402,2018/2/27,红星
1,45870740587,致中和 韧劲酒香 35度低度小酒125ml 酒厂直供,12.6,115,致中和,满2件7.5折,1750,2018/2/27,致中和
2,43211682074,红星二锅头酒大二绿瓶56度 500ml清香型白酒酒厂直供,13.0,8703,整箱原厂包装 见详情链接,满99元减10元,22575,2018/2/27,红星
3,43261836143,42度牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒,13.0,12722,正宗牛栏山 地道北京味,NaN,18083,2018/2/27,牛栏山
4,540741239830,致中和35度小百年白酒125ml/瓶 建德特产 酒厂直供,15.0,28,NaN,NaN,3103,2018/2/27,致中和
5,44646135143,四特酒莲四系列莲四52度 500ml特香型白酒江西名酒酒厂直供,16.0,203,特香典范 中国四特 猫超自营 百城次日达,NaN,2469,2018/2/27,四特
6,533909289770,汾酒 山西杏花村竹叶青酒38度玻竹150ml清香型酒,17.5,143,竹叶青 露酒,NaN,1133,2018/2/27,汾酒
7,542806723433,泸州老窖泸小二 42度 125ml 中度 白酒,18.0,79,NaN,NaN,941,2018/2/27,泸州老窖
8,525051924381,洋河 绿敦煌大曲 42度500ml 浓香型白酒 猫超自营,19.0,1187,敦煌大曲 老牌名酒,NaN,2404,2018/2/27,洋河
9,533767751992,牛栏山42度塑桶二锅头2L 清香型桶装白酒特价大牛桶,19.9,2029,正宗牛栏山 地道北京味,NaN,7060,2018/2/27,牛栏山
10,538705671233,安达情闷倒驴60度圆钢壶750ml单瓶装清香型白酒,19.9,218,纯粮高度酒 好喝不上头,NaN,364,2018/2/27,安达情
11,540011154689,泸州老窖 泸州原浆柔和 52度 500mL 白酒浓香型,20.0,3116,NaN,NaN,25921,2018/2/27,泸州老窖
12,523751557195,红星二锅头大二56度 750ml酒厂直供包装更新中,20.0,763,老百姓爱喝的二锅头 天猫自营 百城次日达,满99元减10元,2253,2018/2/27,红星
13,551838729137,【天猫超市】双沟青优42度200ml猫超新品小酒超值优惠酒厂直供,20.0,49,NaN,NaN,325,2018/2/27,双沟
14,562468261759,劲牌劲酒公司和露酒玫瑰花香型8度275mL单瓶装,20.0,89,NaN,NaN,17,2018/2/27,劲牌
15,562989357827,牛栏山52度珍品陈酿（银牛）150ml浓香型小瓶白酒,24.0,4,NaN,NaN,0,2018/2/27,牛栏山
16,523749894366,红星二锅头酒绵柔8陈酿蓝瓶43度500ml白酒酒厂直供,27.0,1677,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,3074,2018/2/27,红星
17,556738841682,牛栏山42度2L桶装二锅头+精武鸭锁骨150g组合装,27.9,30,NaN,NaN,76,2018/2/27,牛栏山
18,537013830676,江小白品鉴酒更多优惠请见详情页非卖品请勿下单！,29.0,121,单纯高粱酿造 精制包装 特色语录,NaN,67514,2018/2/27,江小白
19,521044476993,致中和果酒 青梅酒10度白酒200ml/瓶聚会女生用酒,29.0,415,整箱更优惠,满2件7.5折,10230,2018/2/27,致中和
20,45809251206,致中和白酒莲子酒42度125ml/瓶建德特产酒厂直供,29.0,27,本土红莲酿造 口感清雅醇香,满2件7.5折,4066,2018/2/27,致中和
21,552360897943,古井特曲50度500ml浓香白酒古井贡酒股份平价酒,29.0,71,古井特曲,满99元减30元,1827,2018/2/27,古井贡酒
22,530440341343,牛栏山二锅头白酒 出口美国型56度750ml 清香型白酒,29.9,215,正宗牛栏山 地道北京味 正品特惠,NaN,850,2018/2/27,牛栏山
23,35263656074,红星二锅头酒苏扁50度 500ml清香型白酒酒厂直供,34.0,348,老百姓爱喝的二锅头 天猫自营 百城次日达,满99元减10元,693,2018/2/27,红星
24,541217125531,劲牌劲酒公司露酒32度追风活力500ml 瓶装 白酒,35.0,955,品味美酒,满2件5折,2473,2018/2/27,劲酒
25,523751413489,红星二锅头酒绵柔8陈酿蓝瓶43度 750ml白酒酒厂直供,37.0,1252,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,4962,2018/2/27,红星
26,533909513991,汾酒 山西杏花村竹叶青酒38度玻竹475ml清香型酒,37.9,535,竹叶青 露酒,NaN,2874,2018/2/27,汾酒
27,533859373238,牛栏山珍品陈酿52度(金牛)500ml浓香型新品金牛,38.0,66,正宗牛栏山 地道北京味,NaN,347,2018/2/27,牛栏山
28,523726503584,红星二锅头酒绵柔8陈酿53度 750ml白酒酒厂直供,38.9,1085,老百姓爱喝的二锅头 满减更优惠 天猫自营,满99元减10元,5856,2018/2/27,红星
29,533832146187,牛栏山(金牛)珍品陈酿39度500ml浓香型 珍品金牛,39.0,116,正宗牛栏山 地道北京味,NaN,806,2018/2/27,牛栏山
...,...,...,...,...,...,...,...,...,...
852,536493211279,水井坊臻酿八号6瓶装52度500ml*6整箱装浓香型白酒,2129.0,209,天猫自营百城次日达 正品保障 品质无忧,NaN,350,2018/2/27,水井坊
853,40556587702,郎酒 红花郎十 53度500mlx6瓶 酱香型 整箱 白酒,2148.0,21,原箱发货（内含礼袋),NaN,196,2018/2/27,郎酒
854,39256922715,52度洋河天之蓝 480ml*6瓶 绵柔型白酒 猫超配送,2178.0,161,不参与天猫超市任何优惠券活动,NaN,516,2018/2/27,洋河
855,543899438700,郎酒青花郎20年53度500ml×2瓶酱香型白酒双支礼袋装,2196.0,110,NaN,NaN,220,2018/2/27,郎酒
856,561267590798,52度洋河天之蓝520ml*6 绵柔型白酒 猫超新品 酒厂直供,2208.0,69,NaN,NaN,22,2018/2/27,洋河
857,553826161701,郎酒红花郎十 53度558mlx6瓶 酱香型高度白酒整箱,2258.0,43,整箱装 内含礼袋,NaN,66,2018/2/27,郎酒
858,555705473809,习酒窖藏1988雅致版53度500ml*4整箱装酱香型白酒,2272.0,66,NaN,满1件送任意1件赠品（赠完即止）,67,2018/2/27,习酒
859,537385391122,牛栏山经典二锅头52度500ml*6整箱装清香型白酒,2288.0,23,正宗牛栏山 地道北京味 箱内礼袋3支,NaN,15,2018/2/27,牛栏山
860,538022692116,白云边20年陈酿粮食酒42度白酒500mL*6瓶整箱特价,2328.0,27,湖北名酒 品牌名酒 纯粮发酵 精细制曲,NaN,26,2018/2/27,白云边
861,540450214555,汾酒杏花村42度青花20清香型白酒500ml*6酒厂直供,2328.0,4,官方授权 天猫配送 保真快捷,NaN,17,2018/2/27,汾酒
862,532583189339,52度剑南春白酒500ml*6整箱酒厂直供不参加任何活动,2388.0,422,不参与天猫超市任何优惠券活动,NaN,788,2018/2/27,剑南春
863,530899370324,茅台赖茅传承-蓝酱香型白酒53度500ml*6酒厂直供,2390.0,60,赖茅不赖 酱香型酒,满2000元减600元；满4000元减1376元,311,2018/2/27,茅台
864,526117179063,汾酒杏花村53度汾酒青花20清香型白酒500ml*6瓶整箱,2448.0,54,官方授权 天猫配送 保真快捷,NaN,107,2018/2/27,汾酒
865,538317516423,五粮液股份52度尊耀珍酿级500ml*30瓶浓香型白酒,2495.0,3,酒味醇厚甘美，喷香浓郁,满999元减150元,21,2018/2/27,五粮液
866,561462254223,茅台赖茅珍品53度500ml*6瓶酱香型白酒酒厂直供,2760.0,37,赖茅珍品，酒厂直供,满1000元减200元,10,2018/2/27,赖茅
867,555779615538,45度洋河梦之蓝M6- 500ml*4 绵柔型白酒 猫超配送 酒厂直供,2796.0,29,NaN,NaN,13,2018/2/27,洋河
868,548477375633,水井坊井台装38度 500ml*6白酒整箱浓香礼盒酒厂直供,2849.0,2,天猫超市自营 百城次日达 品质保证,NaN,5,2018/2/27,水井坊
869,555781135649,52度洋河梦之蓝M6-52度500ml*4 绵柔型白酒 酒厂直供,2912.0,73,NaN,NaN,42,2018/2/27,洋河
870,553612984990,剑南春52度珍藏级天益老号浓香型白酒500ml*6原箱装,2988.0,21,不参与天猫超市任何优惠券活动,NaN,18,2018/2/27,剑南春
871,523188746217,飞天茅台现货53度酱香白酒500ml*2非整箱发货限购1组,2998.0,21685,不参与天猫超市任何优惠券活动,NaN,17980,2018/2/27,茅台
872,537910992262,水井坊井台52度浓香型500mlX6瓶白酒礼盒装酒厂直供,3089.0,29,天猫自营百城次日达 正品保障 品质无忧,NaN,85,2018/2/27,水井坊
873,555744106584,【天猫超市】泸州老窖国窖1573手工版53度 500mLX4整箱浓香型白酒,3240.0,3,NaN,NaN,5,2018/2/27,泸州老窖
874,543781878245,郎酒红花郎15年53度500ml *6瓶酱香白酒酒厂直供,3388.0,77,NaN,满1件送任意1件赠品（赠完即止）,133,2018/2/27,郎酒
875,561459170962,茅台赖茅珍藏53度500ml*6瓶酱香型国产白酒酒厂直供,3399.0,30,NaN,满1000元减200元,21,2018/2/27,赖茅
876,540443712492,汾酒杏花村53度青花30清香型500ml*6整箱酒厂直供,3988.0,31,官方授权 天猫配送 保真快捷,NaN,42,2018/2/27,汾酒
877,521600593441,泸州老窖国窖1573白酒 52度500ml*6瓶整箱装礼品装酒厂直供,5240.0,53,领劵立减200元，好酒不打烊,满1件送任意2件赠品（赠完即止）,153,2018/2/27,泸州老窖
878,538282333692,52度五粮液普五500ml*6猫超自采不参加任何活动,5599.0,473,不参与天猫超市任何优惠券活动,NaN,614,2018/2/27,五粮液
879,540103784273,白酒五粮液1618陶瓷瓶500ml*6原箱装酒水名酒礼盒,5639.0,35,NaN,NaN,61,2018/2/27,五粮液
880,543796215762,郎酒青花郎20年53度500ml*6瓶酱香白酒酒厂直供,6588.0,57,NaN,满1件送任意1件赠品（赠完即止）,114,2018/2/27,郎酒
881,522004673739,五粮液普五52度 500ml*2礼盒装猫超直采高度白酒,NaN,1292,不参与天猫超市任何优惠券活动,满2198元减200元,1319,2018/2/27,五粮液

In [124]:
wine.商品名称.str.replace('ml',"ML")

0                 红星二锅头酒白扁56度100ML瓶装清香型白酒小扁二
1                 致中和 韧劲酒香 35度低度小酒125ML 酒厂直供
2               红星二锅头酒大二绿瓶56度 500ML清香型白酒酒厂直供
3                42度牛栏山陈酿500ML 二锅头白酒白牛 浓香型白酒
4               致中和35度小百年白酒125ML/瓶 建德特产 酒厂直供
5            四特酒莲四系列莲四52度 500ML特香型白酒江西名酒酒厂直供
6                 汾酒 山西杏花村竹叶青酒38度玻竹150ML清香型酒
7                    泸州老窖泸小二 42度 125ML 中度 白酒
8               洋河 绿敦煌大曲 42度500ML 浓香型白酒 猫超自营
9                 牛栏山42度塑桶二锅头2L 清香型桶装白酒特价大牛桶
10                 安达情闷倒驴60度圆钢壶750ML单瓶装清香型白酒
11               泸州老窖 泸州原浆柔和 52度 500mL 白酒浓香型
12                 红星二锅头大二56度 750ML酒厂直供包装更新中
13          【天猫超市】双沟青优42度200ML猫超新品小酒超值优惠酒厂直供
14                  劲牌劲酒公司和露酒玫瑰花香型8度275mL单瓶装
15                牛栏山52度珍品陈酿（银牛）150ML浓香型小瓶白酒
16               红星二锅头酒绵柔8陈酿蓝瓶43度500ML白酒酒厂直供
17                牛栏山42度2L桶装二锅头+精武鸭锁骨150g组合装
18                   江小白品鉴酒更多优惠请见详情页非卖品请勿下单！
19               致中和果酒 青梅酒10度白酒200ML/瓶聚会女生用酒
20                致中和白酒莲子酒42度125ML/瓶建德特产酒厂直供
21                 古井特曲50度500ML浓香白酒古井贡酒股份平价酒
22              牛栏山二锅头白酒 出口美国型56度750ML 清香型白酒
23                红星二锅头酒苏扁50度 500ML清香型白酒酒厂直供
24                劲牌劲酒公司露酒32度追风活力500ML 瓶装 白酒
25              红星二锅头酒绵柔8陈酿蓝瓶43度 750ML白酒酒厂直供
26                汾酒 山西杏花村竹叶青酒38度玻竹475ML清香型酒
27                牛栏山珍品陈酿52度(金牛)500ML浓香型新品金牛
28                红星二锅头酒绵柔8陈酿53度 750ML白酒酒厂直供
29               牛栏山(金牛)珍品陈酿39度500ML浓香型 珍品金牛
                       ...
852             水井坊臻酿八号6瓶装52度500ML*6整箱装浓香型白酒
853            郎酒 红花郎十 53度500MLx6瓶 酱香型 整箱 白酒
854             52度洋河天之蓝 480ML*6瓶 绵柔型白酒 猫超配送
855            郎酒青花郎20年53度500ML×2瓶酱香型白酒双支礼袋装
856          52度洋河天之蓝520ML*6 绵柔型白酒 猫超新品 酒厂直供
857             郎酒红花郎十 53度558MLx6瓶 酱香型高度白酒整箱
858            习酒窖藏1988雅致版53度500ML*4整箱装酱香型白酒
859               牛栏山经典二锅头52度500ML*6整箱装清香型白酒
860             白云边20年陈酿粮食酒42度白酒500mL*6瓶整箱特价
861             汾酒杏花村42度青花20清香型白酒500ML*6酒厂直供
862             52度剑南春白酒500ML*6整箱酒厂直供不参加任何活动
863              茅台赖茅传承-蓝酱香型白酒53度500ML*6酒厂直供
864            汾酒杏花村53度汾酒青花20清香型白酒500ML*6瓶整箱
865              五粮液股份52度尊耀珍酿级500ML*30瓶浓香型白酒
866               茅台赖茅珍品53度500ML*6瓶酱香型白酒酒厂直供
867      45度洋河梦之蓝M6- 500ML*4 绵柔型白酒 猫超配送 酒厂直供
868            水井坊井台装38度 500ML*6白酒整箱浓香礼盒酒厂直供
869         52度洋河梦之蓝M6-52度500ML*4 绵柔型白酒 酒厂直供
870             剑南春52度珍藏级天益老号浓香型白酒500ML*6原箱装
871            飞天茅台现货53度酱香白酒500ML*2非整箱发货限购1组
872             水井坊井台52度浓香型500MLX6瓶白酒礼盒装酒厂直供
873    【天猫超市】泸州老窖国窖1573手工版53度 500mLX4整箱浓香型白酒
874             郎酒红花郎15年53度500ML *6瓶酱香白酒酒厂直供
875             茅台赖茅珍藏53度500ML*6瓶酱香型国产白酒酒厂直供
876             汾酒杏花村53度青花30清香型500ML*6整箱酒厂直供
877       泸州老窖国窖1573白酒 52度500ML*6瓶整箱装礼品装酒厂直供
878               52度五粮液普五500ML*6猫超自采不参加任何活动
879             白酒五粮液1618陶瓷瓶500ML*6原箱装酒水名酒礼盒
880              郎酒青花郎20年53度500ML*6瓶酱香白酒酒厂直供
881              五粮液普五52度 500ML*2礼盒装猫超直采高度白酒
Name: 商品名称, Length: 882, dtype: object

In [125]:
wine.商品名称.str.replace('度','°')

0                 红星二锅头酒白扁56°100ml瓶装清香型白酒小扁二
1                 致中和 韧劲酒香 35°低°小酒125ml 酒厂直供
2               红星二锅头酒大二绿瓶56° 500ml清香型白酒酒厂直供
3                42°牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒
4               致中和35°小百年白酒125ml/瓶 建德特产 酒厂直供
5            四特酒莲四系列莲四52° 500ml特香型白酒江西名酒酒厂直供
6                 汾酒 山西杏花村竹叶青酒38°玻竹150ml清香型酒
7                    泸州老窖泸小二 42° 125ml 中° 白酒
8               洋河 绿敦煌大曲 42°500ml 浓香型白酒 猫超自营
9                 牛栏山42°塑桶二锅头2L 清香型桶装白酒特价大牛桶
10                 安达情闷倒驴60°圆钢壶750ml单瓶装清香型白酒
11               泸州老窖 泸州原浆柔和 52° 500mL 白酒浓香型
12                 红星二锅头大二56° 750ml酒厂直供包装更新中
13          【天猫超市】双沟青优42°200ml猫超新品小酒超值优惠酒厂直供
14                  劲牌劲酒公司和露酒玫瑰花香型8°275mL单瓶装
15                牛栏山52°珍品陈酿（银牛）150ml浓香型小瓶白酒
16               红星二锅头酒绵柔8陈酿蓝瓶43°500ml白酒酒厂直供
17                牛栏山42°2L桶装二锅头+精武鸭锁骨150g组合装
18                   江小白品鉴酒更多优惠请见详情页非卖品请勿下单！
19               致中和果酒 青梅酒10°白酒200ml/瓶聚会女生用酒
20                致中和白酒莲子酒42°125ml/瓶建德特产酒厂直供
21                 古井特曲50°500ml浓香白酒古井贡酒股份平价酒
22              牛栏山二锅头白酒 出口美国型56°750ml 清香型白酒
23                红星二锅头酒苏扁50° 500ml清香型白酒酒厂直供
24                劲牌劲酒公司露酒32°追风活力500ml 瓶装 白酒
25              红星二锅头酒绵柔8陈酿蓝瓶43° 750ml白酒酒厂直供
26                汾酒 山西杏花村竹叶青酒38°玻竹475ml清香型酒
27                牛栏山珍品陈酿52°(金牛)500ml浓香型新品金牛
28                红星二锅头酒绵柔8陈酿53° 750ml白酒酒厂直供
29               牛栏山(金牛)珍品陈酿39°500ml浓香型 珍品金牛
                       ...
852             水井坊臻酿八号6瓶装52°500ml*6整箱装浓香型白酒
853            郎酒 红花郎十 53°500mlx6瓶 酱香型 整箱 白酒
854             52°洋河天之蓝 480ml*6瓶 绵柔型白酒 猫超配送
855            郎酒青花郎20年53°500ml×2瓶酱香型白酒双支礼袋装
856          52°洋河天之蓝520ml*6 绵柔型白酒 猫超新品 酒厂直供
857             郎酒红花郎十 53°558mlx6瓶 酱香型高°白酒整箱
858            习酒窖藏1988雅致版53°500ml*4整箱装酱香型白酒
859               牛栏山经典二锅头52°500ml*6整箱装清香型白酒
860             白云边20年陈酿粮食酒42°白酒500mL*6瓶整箱特价
861             汾酒杏花村42°青花20清香型白酒500ml*6酒厂直供
862             52°剑南春白酒500ml*6整箱酒厂直供不参加任何活动
863              茅台赖茅传承-蓝酱香型白酒53°500ml*6酒厂直供
864            汾酒杏花村53°汾酒青花20清香型白酒500ml*6瓶整箱
865              五粮液股份52°尊耀珍酿级500ml*30瓶浓香型白酒
866               茅台赖茅珍品53°500ml*6瓶酱香型白酒酒厂直供
867      45°洋河梦之蓝M6- 500ml*4 绵柔型白酒 猫超配送 酒厂直供
868            水井坊井台装38° 500ml*6白酒整箱浓香礼盒酒厂直供
869         52°洋河梦之蓝M6-52°500ml*4 绵柔型白酒 酒厂直供
870             剑南春52°珍藏级天益老号浓香型白酒500ml*6原箱装
871            飞天茅台现货53°酱香白酒500ml*2非整箱发货限购1组
872             水井坊井台52°浓香型500mlX6瓶白酒礼盒装酒厂直供
873    【天猫超市】泸州老窖国窖1573手工版53° 500mLX4整箱浓香型白酒
874             郎酒红花郎15年53°500ml *6瓶酱香白酒酒厂直供
875             茅台赖茅珍藏53°500ml*6瓶酱香型国产白酒酒厂直供
876             汾酒杏花村53°青花30清香型500ml*6整箱酒厂直供
877       泸州老窖国窖1573白酒 52°500ml*6瓶整箱装礼品装酒厂直供
878               52°五粮液普五500ml*6猫超自采不参加任何活动
879             白酒五粮液1618陶瓷瓶500ml*6原箱装酒水名酒礼盒
880              郎酒青花郎20年53°500ml*6瓶酱香白酒酒厂直供
881              五粮液普五52° 500ml*2礼盒装猫超直采高°白酒
Name: 商品名称, Length: 882, dtype: object

#### 普通的 pandas 中的 replace

这个 repalce 和 str 向量化后的 repalce 有很大的不同,这个是对整个字符串进行替换.

In [128]:
wine.品牌.replace('红星','蓝星')

0        蓝星
1       致中和
2        蓝星
3       牛栏山
4       致中和
5        四特
6        汾酒
7      泸州老窖
8        洋河
9       牛栏山
10      安达情
11     泸州老窖
12       蓝星
13       双沟
14       劲牌
15      牛栏山
16       蓝星
17      牛栏山
18      江小白
19      致中和
20      致中和
21     古井贡酒
22      牛栏山
23       蓝星
24       劲酒
25       蓝星
26       汾酒
27      牛栏山
28       蓝星
29      牛栏山
       ...
852     水井坊
853      郎酒
854      洋河
855      郎酒
856      洋河
857      郎酒
858      习酒
859     牛栏山
860     白云边
861      汾酒
862     剑南春
863      茅台
864      汾酒
865     五粮液
866      赖茅
867      洋河
868     水井坊
869      洋河
870     剑南春
871      茅台
872     水井坊
873    泸州老窖
874      郎酒
875      赖茅
876      汾酒
877    泸州老窖
878     五粮液
879     五粮液
880      郎酒
881     五粮液
Name: 品牌, Length: 882, dtype: object

In [129]:
wine.品牌.replace({'红星':'黑心','致中和':'致青春'})

0        黑心
1       致青春
2        黑心
3       牛栏山
4       致青春
5        四特
6        汾酒
7      泸州老窖
8        洋河
9       牛栏山
10      安达情
11     泸州老窖
12       黑心
13       双沟
14       劲牌
15      牛栏山
16       黑心
17      牛栏山
18      江小白
19      致青春
20      致青春
21     古井贡酒
22      牛栏山
23       黑心
24       劲酒
25       黑心
26       汾酒
27      牛栏山
28       黑心
29      牛栏山
       ...
852     水井坊
853      郎酒
854      洋河
855      郎酒
856      洋河
857      郎酒
858      习酒
859     牛栏山
860     白云边
861      汾酒
862     剑南春
863      茅台
864      汾酒
865     五粮液
866      赖茅
867      洋河
868     水井坊
869      洋河
870     剑南春
871      茅台
872     水井坊
873    泸州老窖
874      郎酒
875      赖茅
876      汾酒
877    泸州老窖
878     五粮液
879     五粮液
880      郎酒
881     五粮液
Name: 品牌, Length: 882, dtype: object

### 其他方法

In [64]:
# get方法
wine.商品名称.str.get(1)

0      星
1      中
2      星
3      2
4      中
5      特
6      酒
7      州
8      河
9      栏
10     达
11     州
12     星
13     天
14     牌
15     栏
16     星
17     栏
18     小
19     中
20     中
21     井
22     栏
23     星
24     牌
25     星
26     酒
27     栏
28     星
29     栏
      ..
852    井
853    酒
854    2
855    酒
856    2
857    酒
858    酒
859    栏
860    云
861    酒
862    2
863    台
864    酒
865    粮
866    台
867    5
868    井
869    2
870    南
871    天
872    井
873    天
874    酒
875    台
876    酒
877    州
878    2
879    酒
880    酒
881    粮
Name: 商品名称, Length: 882, dtype: object

In [133]:
# slice 进行截取
wine.商品名称.str.slice(0,3)

0      红星二
1      致中和
2      红星二
3      42度
4      致中和
5      四特酒
6      汾酒
7      泸州老
8      洋河
9      牛栏山
10     安达情
11     泸州老
12     红星二
13     【天猫
14     劲牌劲
15     牛栏山
16     红星二
17     牛栏山
18     江小白
19     致中和
20     致中和
21     古井特
22     牛栏山
23     红星二
24     劲牌劲
25     红星二
26     汾酒
27     牛栏山
28     红星二
29     牛栏山
      ...
852    水井坊
853    郎酒
854    52度
855    郎酒青
856    52度
857    郎酒红
858    习酒窖
859    牛栏山
860    白云边
861    汾酒杏
862    52度
863    茅台赖
864    汾酒杏
865    五粮液
866    茅台赖
867    45度
868    水井坊
869    52度
870    剑南春
871    飞天茅
872    水井坊
873    【天猫
874    郎酒红
875    茅台赖
876    汾酒杏
877    泸州老
878    52度
879    白酒五
880    郎酒青
881    五粮液
Name: 商品名称, Length: 882, dtype: object

In [138]:
# slice_replace 对元素进行切片替换
wine.商品名称.str.slice_replace(0,3,'你好')

0                 你好锅头酒白扁56度100ml瓶装清香型白酒小扁二
1                 你好 韧劲酒香 35度低度小酒125ml 酒厂直供
2               你好锅头酒大二绿瓶56度 500ml清香型白酒酒厂直供
3                你好牛栏山陈酿500ml 二锅头白酒白牛 浓香型白酒
4               你好35度小百年白酒125ml/瓶 建德特产 酒厂直供
5            你好莲四系列莲四52度 500ml特香型白酒江西名酒酒厂直供
6                 你好山西杏花村竹叶青酒38度玻竹150ml清香型酒
7                    你好窖泸小二 42度 125ml 中度 白酒
8               你好绿敦煌大曲 42度500ml 浓香型白酒 猫超自营
9                 你好42度塑桶二锅头2L 清香型桶装白酒特价大牛桶
10                 你好闷倒驴60度圆钢壶750ml单瓶装清香型白酒
11               你好窖 泸州原浆柔和 52度 500mL 白酒浓香型
12                 你好锅头大二56度 750ml酒厂直供包装更新中
13          你好超市】双沟青优42度200ml猫超新品小酒超值优惠酒厂直供
14                  你好酒公司和露酒玫瑰花香型8度275mL单瓶装
15                你好52度珍品陈酿（银牛）150ml浓香型小瓶白酒
16               你好锅头酒绵柔8陈酿蓝瓶43度500ml白酒酒厂直供
17                你好42度2L桶装二锅头+精武鸭锁骨150g组合装
18                   你好品鉴酒更多优惠请见详情页非卖品请勿下单！
19               你好果酒 青梅酒10度白酒200ml/瓶聚会女生用酒
20                你好白酒莲子酒42度125ml/瓶建德特产酒厂直供
21                 你好曲50度500ml浓香白酒古井贡酒股份平价酒
22              你好二锅头白酒 出口美国型56度750ml 清香型白酒
23                你好锅头酒苏扁50度 500ml清香型白酒酒厂直供
24                你好酒公司露酒32度追风活力500ml 瓶装 白酒
25              你好锅头酒绵柔8陈酿蓝瓶43度 750ml白酒酒厂直供
26                你好山西杏花村竹叶青酒38度玻竹475ml清香型酒
27                你好珍品陈酿52度(金牛)500ml浓香型新品金牛
28                你好锅头酒绵柔8陈酿53度 750ml白酒酒厂直供
29               你好(金牛)珍品陈酿39度500ml浓香型 珍品金牛
                       ...
852             你好臻酿八号6瓶装52度500ml*6整箱装浓香型白酒
853            你好红花郎十 53度500mlx6瓶 酱香型 整箱 白酒
854             你好洋河天之蓝 480ml*6瓶 绵柔型白酒 猫超配送
855            你好花郎20年53度500ml×2瓶酱香型白酒双支礼袋装
856          你好洋河天之蓝520ml*6 绵柔型白酒 猫超新品 酒厂直供
857             你好花郎十 53度558mlx6瓶 酱香型高度白酒整箱
858            你好藏1988雅致版53度500ml*4整箱装酱香型白酒
859               你好经典二锅头52度500ml*6整箱装清香型白酒
860             你好20年陈酿粮食酒42度白酒500mL*6瓶整箱特价
861             你好花村42度青花20清香型白酒500ml*6酒厂直供
862             你好剑南春白酒500ml*6整箱酒厂直供不参加任何活动
863              你好茅传承-蓝酱香型白酒53度500ml*6酒厂直供
864            你好花村53度汾酒青花20清香型白酒500ml*6瓶整箱
865              你好股份52度尊耀珍酿级500ml*30瓶浓香型白酒
866               你好茅珍品53度500ml*6瓶酱香型白酒酒厂直供
867      你好洋河梦之蓝M6- 500ml*4 绵柔型白酒 猫超配送 酒厂直供
868            你好井台装38度 500ml*6白酒整箱浓香礼盒酒厂直供
869         你好洋河梦之蓝M6-52度500ml*4 绵柔型白酒 酒厂直供
870             你好52度珍藏级天益老号浓香型白酒500ml*6原箱装
871            你好台现货53度酱香白酒500ml*2非整箱发货限购1组
872             你好井台52度浓香型500mlX6瓶白酒礼盒装酒厂直供
873    你好超市】泸州老窖国窖1573手工版53度 500mLX4整箱浓香型白酒
874             你好花郎15年53度500ml *6瓶酱香白酒酒厂直供
875             你好茅珍藏53度500ml*6瓶酱香型国产白酒酒厂直供
876             你好花村53度青花30清香型500ml*6整箱酒厂直供
877       你好窖国窖1573白酒 52度500ml*6瓶整箱装礼品装酒厂直供
878               你好五粮液普五500ml*6猫超自采不参加任何活动
879             你好粮液1618陶瓷瓶500ml*6原箱装酒水名酒礼盒
880              你好花郎20年53度500ml*6瓶酱香白酒酒厂直供
881              你好普五52度 500ml*2礼盒装猫超直采高度白酒
Name: 商品名称, Length: 882, dtype: object

In [136]:
wine['new_ID']=wine.ID.astype('str').str.slice_replace(-3,repl='000')

In [142]:
# cat 对字符串进行连接
grade.姓名.str.cat(sep=', ')

'杨璐, 王雪, 韩林霖, 沙龙逸, 李鉴学, 韩雨萌, 刘帅, 康惠雯, 刘钰婷, 林世博, 张希, 徐冲, 苑宇飞, 卢一凡, 张瑞鑫, 范作鑫, 裴子翔, 武传禹, 任雪桐, 刘姗, 王柏坤, 赵永刚, 张馨月大, 张曦月, 胡丁文, 赵美欣, 赵殿宇, 张智文, 李季, 杨加晖, 何旭, 张智凯, 张晓爽, 姜美慧, 张埕镒, 贺俊文, 张馨月小, 代诗涵, 艾宇, 黄俊焯, 邹建志, 张俊奎, 孙波, 张良, 王春月, 代明哲, 张开羽, 狄建译, 张家硕, 郭娜, 周坤, 洪禹, 王治超, 臧云飞, 袁茂哲, 丁婉艺, 于娇莹, 刘旭辉, 张宇婷, 黄明涛, 吕文卓, 王晟煜, 孙龙基, 赵森, 满朝升, 李忠浩, 侯禹志, 尹鸿涛'

In [147]:
# repeat 
imdb.genre.str.repeat(4)

0                      CrimeCrimeCrimeCrime
1                      CrimeCrimeCrimeCrime
2                      CrimeCrimeCrimeCrime
3                  ActionActionActionAction
4                      CrimeCrimeCrimeCrime
5                      DramaDramaDramaDrama
6              WesternWesternWesternWestern
7      AdventureAdventureAdventureAdventure
8      BiographyBiographyBiographyBiography
9                      DramaDramaDramaDrama
10     AdventureAdventureAdventureAdventure
11                 ActionActionActionAction
12                 ActionActionActionAction
13                     DramaDramaDramaDrama
14     AdventureAdventureAdventureAdventure
15     AdventureAdventureAdventureAdventure
16                     DramaDramaDramaDrama
17                     DramaDramaDramaDrama
18     BiographyBiographyBiographyBiography
19                 ActionActionActionAction
20                 ActionActionActionAction
21                     CrimeCrimeCrimeCrime
22                     DramaDramaDramaDrama
23                     CrimeCrimeCrimeCrime
24                     DramaDramaDramaDrama
25                 ComedyComedyComedyComedy
26             WesternWesternWesternWestern
27                     DramaDramaDramaDrama
28                     CrimeCrimeCrimeCrime
29                 ComedyComedyComedyComedy
                       ...
949                ComedyComedyComedyComedy
950                    CrimeCrimeCrimeCrime
951                    DramaDramaDramaDrama
952                ComedyComedyComedyComedy
953    AdventureAdventureAdventureAdventure
954                ActionActionActionAction
955                    DramaDramaDramaDrama
956                ComedyComedyComedyComedy
957                ComedyComedyComedyComedy
958                    DramaDramaDramaDrama
959                ComedyComedyComedyComedy
960                ComedyComedyComedyComedy
961    BiographyBiographyBiographyBiography
962                ComedyComedyComedyComedy
963                ActionActionActionAction
964    BiographyBiographyBiographyBiography
965            MysteryMysteryMysteryMystery
966    AnimationAnimationAnimationAnimation
967                ActionActionActionAction
968                    DramaDramaDramaDrama
969                    CrimeCrimeCrimeCrime
970                    DramaDramaDramaDrama
971                ComedyComedyComedyComedy
972                    DramaDramaDramaDrama
973                    DramaDramaDramaDrama
974                ComedyComedyComedyComedy
975    AdventureAdventureAdventureAdventure
976                ActionActionActionAction
977                HorrorHorrorHorrorHorror
978                    CrimeCrimeCrimeCrime
Name: genre, Length: 979, dtype: object

In [148]:
# 把每个元素重复 n 次
grade.姓名.str.repeat(2)

0         杨璐杨璐
1         王雪王雪
2       韩林霖韩林霖
3       沙龙逸沙龙逸
4       李鉴学李鉴学
5       韩雨萌韩雨萌
6         刘帅刘帅
7       康惠雯康惠雯
8       刘钰婷刘钰婷
9       林世博林世博
10        张希张希
11        徐冲徐冲
12      苑宇飞苑宇飞
13      卢一凡卢一凡
14      张瑞鑫张瑞鑫
15      范作鑫范作鑫
16      裴子翔裴子翔
17      武传禹武传禹
18      任雪桐任雪桐
19        刘姗刘姗
20      王柏坤王柏坤
21      赵永刚赵永刚
22    张馨月大张馨月大
23      张曦月张曦月
24      胡丁文胡丁文
25      赵美欣赵美欣
26      赵殿宇赵殿宇
27      张智文张智文
28        李季李季
29      杨加晖杨加晖
        ...
38        艾宇艾宇
39      黄俊焯黄俊焯
40      邹建志邹建志
41      张俊奎张俊奎
42        孙波孙波
43        张良张良
44      王春月王春月
45      代明哲代明哲
46      张开羽张开羽
47      狄建译狄建译
48      张家硕张家硕
49        郭娜郭娜
50        周坤周坤
51        洪禹洪禹
52      王治超王治超
53      臧云飞臧云飞
54      袁茂哲袁茂哲
55      丁婉艺丁婉艺
56      于娇莹于娇莹
57      刘旭辉刘旭辉
58      张宇婷张宇婷
59      黄明涛黄明涛
60      吕文卓吕文卓
61      王晟煜王晟煜
62      孙龙基孙龙基
63        赵森赵森
64      满朝升满朝升
65      李忠浩李忠浩
66      侯禹志侯禹志
67      尹鸿涛尹鸿涛
Name: 姓名, Length: 68, dtype: object

In [149]:
grade.姓名.str.join(' ')

0         杨 璐
1         王 雪
2       韩 林 霖
3       沙 龙 逸
4       李 鉴 学
5       韩 雨 萌
6         刘 帅
7       康 惠 雯
8       刘 钰 婷
9       林 世 博
10        张 希
11        徐 冲
12      苑 宇 飞
13      卢 一 凡
14      张 瑞 鑫
15      范 作 鑫
16      裴 子 翔
17      武 传 禹
18      任 雪 桐
19        刘 姗
20      王 柏 坤
21      赵 永 刚
22    张 馨 月 大
23      张 曦 月
24      胡 丁 文
25      赵 美 欣
26      赵 殿 宇
27      张 智 文
28        李 季
29      杨 加 晖
       ...
38        艾 宇
39      黄 俊 焯
40      邹 建 志
41      张 俊 奎
42        孙 波
43        张 良
44      王 春 月
45      代 明 哲
46      张 开 羽
47      狄 建 译
48      张 家 硕
49        郭 娜
50        周 坤
51        洪 禹
52      王 治 超
53      臧 云 飞
54      袁 茂 哲
55      丁 婉 艺
56      于 娇 莹
57      刘 旭 辉
58      张 宇 婷
59      黄 明 涛
60      吕 文 卓
61      王 晟 煜
62      孙 龙 基
63        赵 森
64      满 朝 升
65      李 忠 浩
66      侯 禹 志
67      尹 鸿 涛
Name: 姓名, Length: 68, dtype: object

### 生成哑变量

通过 get_dummies 方法可以将字符串转为哑变量，sep 参数是指定哑变量之间的分隔符。来看看效果吧。

In [27]:
grade_new = grade.head(7)
grade_new

    姓名     语文     数学     英语     总分  班名次  姓名长度
0   杨璐  131.0  143.0  144.0  418.0  1.0   2.0
1   王雪  131.0  135.0  144.0  410.0  2.0   2.0
2  韩林霖  127.0  139.0  142.0  408.0  3.0   3.0
3  沙龙逸    NaN  148.0  136.0  407.0  4.0   3.0
4  李鉴学    NaN  135.0  140.0  401.0  5.0   3.0
5  韩雨萌  129.0  133.0  138.0  400.0  6.0   3.0
6   刘帅  116.0  143.0  140.0  399.0  7.0   2.0

假如我们现在由这样一行数据

- 杨璐, A型
- 王雪, B 型
- 韩林霖,O 型
- 沙龙逸,A 型
- 李鉴学,O 型
- 韩雨萌,A 型
- 刘帅,AB 型

In [ ]:
A - 0
B - 1
O - 2
AB - 3

使用数字进行映射
- A:0
- B:1
- AB:2
- O:3

- 杨璐, 0
- 王雪, 1
- 韩林霖,3
- 沙龙逸,0
- 李鉴学,3
- 韩雨萌,0
- 刘帅,2

In [ ]:
"小学" 0 
"初中" 1
"高中" 2
"大学" 3
"研究生" 4
"博士" 5

- 杨璐, A型
- 王雪, B 型
- 韩林霖,O 型
- 沙龙逸,A 型
- 李鉴学,O 型
- 韩雨萌,A 型
- 刘帅,AB 型

|   姓名     | A    | B    | AB   | O    |
| ------ | ---- | ---- | ---- | ---- |
| 杨  璐 |      |      |      |      |
| 王  雪 |      |      |      |      |
| 韩林霖 |      |      |      |      |
| 沙龙逸 |      |      |      |      |
| 李鉴学 |      |      |      |      |
| 韩雨萌 |      |      |      |      |
| 刘  帅 |      |      |      |      |

In [ ]:
One-hot label

|   姓名     | A    | B    | AB   | O    |
| ------ | ---- | ---- | ---- | ---- |
| 杨  璐 |    1  |    0  |   0   |   0   |
| 王  雪 |    0  |    1  |  0    |   0   |
| 韩林霖 |    0  |   0   |   0   |   1   |
| 沙龙逸 |    1  |  0    |   0   |   0   |
| 李鉴学 |   0   |   0   |   0   |    1  |
| 韩雨萌 |    1  |   0   |  0    |  0    |
| 刘  帅 |   0   |   0   |    1  |   0   |

因为根据其中任意三列,可以得到剩下一列的值,所以可以去掉其中的一列数据

|   姓名     | A    | B    | AB   |
| ------ | ---- | ---- | ---- |
| 杨  璐 |    1  |    0  |   0   | 
| 王  雪 |    0  |    1  |  0    | 
| 韩林霖 |    0  |   0   |   0   | 
| 沙龙逸 |    1  |  0    |   0   | 
| 李鉴学 |   0   |   0   |   0   | 
| 韩雨萌 |    1  |   0   |  0    | 
| 刘  帅 |   0   |   0   |    1  |

In [67]:
content_rating = imdb.content_rating.str

In [72]:
dummy = content_rating.get_dummies().iloc[:, :-1]

In [73]:
dummy

     APPROVED  G  GP  NC-17  NOT RATED  PASSED  PG  PG-13  R  TV-MA  UNRATED
0           0  0   0      0          0       0   0      0  1      0        0
1           0  0   0      0          0       0   0      0  1      0        0
2           0  0   0      0          0       0   0      0  1      0        0
3           0  0   0      0          0       0   0      1  0      0        0
4           0  0   0      0          0       0   0      0  1      0        0
5           0  0   0      0          1       0   0      0  0      0        0
6           0  0   0      0          1       0   0      0  0      0        0
7           0  0   0      0          0       0   0      1  0      0        0
8           0  0   0      0          0       0   0      0  1      0        0
9           0  0   0      0          0       0   0      0  1      0        0
10          0  0   0      0          0       0   0      1  0      0        0
11          0  0   0      0          0       0   0      1  0      0        0
12          0  0   0      0          0       0   1      0  0      0        0
13          0  0   0      0          0       0   0      1  0      0        0
14          0  0   0      0          0       0   0      1  0      0        0
15          0  0   0      0          0       0   0      1  0      0        0
16          0  0   0      0          0       0   0      0  1      0        0
17          0  0   0      0          0       0   0      0  0      0        1
18          0  0   0      0          0       0   0      0  1      0        0
19          0  0   0      0          0       0   1      0  0      0        0
20          0  0   0      0          0       0   0      0  1      0        0
21          0  0   0      0          0       0   0      0  1      0        0
22          1  0   0      0          0       0   0      0  0      0        0
23          0  0   0      0          0       0   0      0  1      0        0
24          0  0   0      0          0       0   0      0  1      0        0
25          0  0   0      0          0       0   0      1  0      0        0
26          0  0   0      0          0       0   0      1  0      0        0
27          0  0   0      0          0       0   0      0  1      0        0
28          0  0   0      0          0       0   0      0  1      0        0
29          0  0   0      0          0       1   0      0  0      0        0
..        ... ..  ..    ...        ...     ...  ..    ... ..    ...      ...
949         0  0   0      0          0       0   1      0  0      0        0
950         0  0   0      0          0       0   0      0  1      0        0
951         0  0   0      0          0       0   0      0  1      0        0
952         0  0   0      0          0       0   0      0  1      0        0
953         0  0   0      0          0       0   1      0  0      0        0
954         0  0   0      0          0       0   0      1  0      0        0
955         0  0   0      0          0       0   0      0  1      0        0
956         0  0   0      0          0       0   1      0  0      0        0
957         0  0   0      0          0       0   0      0  1      0        0
958         0  0   0      0          0       0   0      1  0      0        0
959         0  0   0      0          0       0   0      0  1      0        0
960         0  0   0      0          0       0   0      1  0      0        0
961         0  0   0      0          0       0   0      0  1      0        0
962         0  0   0      0          0       0   1      0  0      0        0
963         0  0   0      0          0       0   0      0  1      0        0
964         0  0   0      0          0       0   0      1  0      0        0
965         0  0   0      0          0       0   0      1  0      0        0
966         0  0   0      0          0       0   0      1  0      0        0
967         0  0   0      0          0       0   0      0  1      0        0
968         0  0   0      0          0       0   0      0  1      0        0
969         0  0   0      0          0       0   0      0  1      0        0
970         0  0   0      0          0       0   0      0  1      0        0
971         0  0   0      0          0       0   0      0  1      0        0
972         0  0   0      1          0       0   0      0  0      0        0
973         0  0   0      0          0       0   0      1  0      0        0
974         0  0   0      0          0       0   1      0  0      0        0
975         0  0   0      0          0       0   1      0  0      0        0
976         0  0   0      0          0       0   0      1  0      0        0
977         0  0   0      0          0       0   1      0  0      0        0
978         0  0   0      0          0       0   0      0  1      0        0

[979 rows x 11 columns]

In [77]:
# pd.concat
imdb_new = pd.concat([imdb, dummy] , axis=1 )

In [78]:
# 把刚才做哑变量的这一列删除掉
imdb_new.pop('content_rating')

0              R
1              R
2              R
3          PG-13
4              R
5      NOT RATED
6      NOT RATED
7          PG-13
8              R
9              R
10         PG-13
11         PG-13
12            PG
13         PG-13
14         PG-13
15         PG-13
16             R
17       UNRATED
18             R
19            PG
20             R
21             R
22      APPROVED
23             R
24             R
25         PG-13
26         PG-13
27             R
28             R
29        PASSED
         ...
949           PG
950            R
951            R
952            R
953           PG
954        PG-13
955            R
956           PG
957            R
958        PG-13
959            R
960        PG-13
961            R
962           PG
963            R
964        PG-13
965        PG-13
966        PG-13
967            R
968            R
969            R
970            R
971            R
972        NC-17
973        PG-13
974           PG
975           PG
976        PG-13
977           PG
978            R
Name: content_rating, Length: 979, dtype: object

In [79]:
imdb_new

,star_rating,title,genre,duration,actors_list,APPROVED,G,GP,NC-17,NOT RATED,PASSED,PG,PG-13,R,TV-MA,UNRATED
0,9.3,The Shawshank Redemption,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",0,0,0,0,0,0,0,0,1,0,0
1,9.2,The Godfather,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",0,0,0,0,0,0,0,0,1,0,0
2,9.1,The Godfather: Part II,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",0,0,0,0,0,0,0,0,1,0,0
3,9.0,The Dark Knight,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E...",0,0,0,0,0,0,0,1,0,0,0
4,8.9,Pulp Fiction,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L....",0,0,0,0,0,0,0,0,1,0,0
5,8.9,12 Angry Men,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...",0,0,0,0,1,0,0,0,0,0,0
6,8.9,"The Good, the Bad and the Ugly",Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...",0,0,0,0,1,0,0,0,0,0,0
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...",0,0,0,0,0,0,0,1,0,0,0
8,8.9,Schindler's List,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...",0,0,0,0,0,0,0,0,1,0,0
9,8.9,Fight Club,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh...",0,0,0,0,0,0,0,0,1,0,0
10,8.8,The Lord of the Rings: The Fellowship of the Ring,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl...",0,0,0,0,0,0,0,1,0,0,0
11,8.8,Inception,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...",0,0,0,0,0,0,0,1,0,0,0
12,8.8,Star Wars: Episode V - The Empire Strikes Back,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...",0,0,0,0,0,0,1,0,0,0,0
13,8.8,Forrest Gump,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']",0,0,0,0,0,0,0,1,0,0,0
14,8.8,The Lord of the Rings: The Two Towers,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort...",0,0,0,0,0,0,0,1,0,0,0
15,8.7,Interstellar,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J...",0,0,0,0,0,0,0,1,0,0,0
16,8.7,One Flew Over the Cuckoo's Nest,Drama,133,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich...",0,0,0,0,0,0,0,0,1,0,0
17,8.7,Seven Samurai,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...",0,0,0,0,0,0,0,0,0,0,1
18,8.7,Goodfellas,Biography,146,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']",0,0,0,0,0,0,0,0,1,0,0
19,8.7,Star Wars,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...",0,0,0,0,0,0,1,0,0,0,0
20,8.7,The Matrix,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car...",0,0,0,0,0,0,0,0,1,0,0
21,8.7,City of God,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael...",0,0,0,0,0,0,0,0,1,0,0
22,8.7,It's a Wonderful Life,Drama,130,"[u'James Stewart', u'Donna Reed', u'Lionel Bar...",1,0,0,0,0,0,0,0,0,0,0
23,8.7,The Usual Suspects,Crime,106,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa...",0,0,0,0,0,0,0,0,1,0,0
24,8.7,Se7en,Drama,127,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac...",0,0,0,0,0,0,0,0,1,0,0
25,8.6,Life Is Beautiful,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G...",0,0,0,0,0,0,0,1,0,0,0
26,8.6,Once Upon a Time in the West,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia...",0,0,0,0,0,0,0,1,0,0,0
27,8.6,The Silence of the Lambs,Drama,118,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren...",0,0,0,0,0,0,0,0,1,0,0
28,8.6,Leon: The Professional,Crime,110,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm...",0,0,0,0,0,0,0,0,1,0,0
29,8.6,City Lights,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F...",0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,7.4,Home Alone,Comedy,103,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St...",0,0,0,0,0,0,1,0,0,0,0
950,7.4,Bound,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan...",0,0,0,0,0,0,0,0,1,0,0
951,7.4,Sleepy Hollow,Drama,105,"[u'Johnny Depp', u'Christina Ricci', u'Miranda...",0,0,0,0,0,0,0,0,1,0,0
952,7.4,Pirate Radio,Comedy,117,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N...",0,0,0,0,0,0,0,0,1,0,0
953,7.4,The NeverEnding Story,Adventure,102,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St...",0,0,0,0,0,0,1,0,0,0,0
954,7.4,X-Men,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc...",0,0,0,0,0,0,0,1,0,0,0
955,7.4,Zero Dark Thirty,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri...",0,0,0,0,0,0,0,0,1,0,0
956,7.4,Manhattan Murder Mystery,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']",0,0,0,0,0,0,1,0,0,0,0
957,7.4,National Lampoon's Vacation,Comedy,98,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Imogen...",0,0,0,0,0,0,0,0,1,0,0
958,7.4,My Sister's Keeper,Drama,109,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B...",0,0,0,0,0,0,0,1,0,0,0
959,7.4,Deconstructing Harry,Comedy,96,"[u'Woody Allen', u'Judy Davis', u'Julia Louis-...",0,0,0,0,0,0,0,0,1,0,0
960,7.4,The Way Way Back,Comedy,103,"[u'Steve Carell', u'Toni Collette', u'Allison ...",0,0,0,0,0,0,0,1,0,0,0
961,7.4,Capote,Biography,114,"[u'Philip Seymour Hoffman', u'Clifton Collins ...",0,0,0,0,0,0,0,0,1,0,0
962,7.4,Driving Miss Daisy,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay...",0,0,0,0,0,0,1,0,0,0,0
963,7.4,La Femme Nikita,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F...",0,0,0,0,0,0,0,0,1,0,0
964,7.4,Lincoln,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ...",0,0,0,0,0,0,0,1,0,0,0
965,7.4,Limitless,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor...",0,0,0,0,0,0,0,1,0,0,0
966,7.4,The Simpsons Movie,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy...",0,0,0,0,0,0,0,1,0,0,0
967,7.4,The Rock,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']",0,0,0,0,0,0,0,0,1,0,0
968,7.4,The English Patient,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will...",0,0,0,0,0,0,0,0,1,0,0
969,7.4,Law Abiding Citizen,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']",0,0,0,0,0,0,0,0,1,0,0
970,7.4,Wonder Boys,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc...",0,0,0,0,0,0,0,0,1,0,0
971,7.4,Death at a Funeral,Comedy,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew...",0,0,0,0,0,0,0,0,1,0,0
972,7.4,Blue Valentine,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John...",0,0,0,1,0,0,0,0,0,0,0
973,7.4,The Cider House Rules,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha...",0,0,0,0,0,0,0,1,0,0,0
974,7.4,Tootsie,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G...",0,0,0,0,0,0,1,0,0,0,0
975,7.4,Back to the Future Part III,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma...",0,0,0,0,0,0,1,0,0,0,0
976,7.4,Master and Commander: The Far Side of the World,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo...",0,0,0,0,0,0,0,1,0,0,0
977,7.4,Poltergeist,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr...",0,0,0,0,0,0,1,0,0,0,0
978,7.4,Wall Street,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar...",0,0,0,0,0,0,0,0,1,0,0

In [166]:
imdb.content_rating.value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
PASSED         7
NC-17          7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

In [165]:
# 对电影分级数据进行哑变量变换
imdb.content_rating.str.get_dummies()

,APPROVED,G,GP,NC-17,NOT RATED,PASSED,PG,PG-13,R,TV-MA,UNRATED,X
0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,0,0
9,0,0,0,0,0,0,0,0,1,0,0,0
10,0,0,0,0,0,0,0,1,0,0,0,0
11,0,0,0,0,0,0,0,1,0,0,0,0
12,0,0,0,0,0,0,1,0,0,0,0,0
13,0,0,0,0,0,0,0,1,0,0,0,0
14,0,0,0,0,0,0,0,1,0,0,0,0
15,0,0,0,0,0,0,0,1,0,0,0,0
16,0,0,0,0,0,0,0,0,1,0,0,0
17,0,0,0,0,0,0,0,0,0,0,1,0
18,0,0,0,0,0,0,0,0,1,0,0,0
19,0,0,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,1,0,0,0
21,0,0,0,0,0,0,0,0,1,0,0,0
22,1,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,1,0,0,0
24,0,0,0,0,0,0,0,0,1,0,0,0
25,0,0,0,0,0,0,0,1,0,0,0,0
26,0,0,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,0,0,1,0,0,0
28,0,0,0,0,0,0,0,0,1,0,0,0
29,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
949,0,0,0,0,0,0,1,0,0,0,0,0
950,0,0,0,0,0,0,0,0,1,0,0,0
951,0,0,0,0,0,0,0,0,1,0,0,0
952,0,0,0,0,0,0,0,0,1,0,0,0
953,0,0,0,0,0,0,1,0,0,0,0,0
954,0,0,0,0,0,0,0,1,0,0,0,0
955,0,0,0,0,0,0,0,0,1,0,0,0
956,0,0,0,0,0,0,1,0,0,0,0,0
957,0,0,0,0,0,0,0,0,1,0,0,0
958,0,0,0,0,0,0,0,1,0,0,0,0
959,0,0,0,0,0,0,0,0,1,0,0,0
960,0,0,0,0,0,0,0,1,0,0,0,0
961,0,0,0,0,0,0,0,0,1,0,0,0
962,0,0,0,0,0,0,1,0,0,0,0,0
963,0,0,0,0,0,0,0,0,1,0,0,0
964,0,0,0,0,0,0,0,1,0,0,0,0
965,0,0,0,0,0,0,0,1,0,0,0,0
966,0,0,0,0,0,0,0,1,0,0,0,0
967,0,0,0,0,0,0,0,0,1,0,0,0
968,0,0,0,0,0,0,0,0,1,0,0,0
969,0,0,0,0,0,0,0,0,1,0,0,0
970,0,0,0,0,0,0,0,0,1,0,0,0
971,0,0,0,0,0,0,0,0,1,0,0,0
972,0,0,0,1,0,0,0,0,0,0,0,0
973,0,0,0,0,0,0,0,1,0,0,0,0
974,0,0,0,0,0,0,1,0,0,0,0,0
975,0,0,0,0,0,0,1,0,0,0,0,0
976,0,0,0,0,0,0,0,1,0,0,0,0
977,0,0,0,0,0,0,1,0,0,0,0,0
978,0,0,0,0,0,0,0,0,1,0,0,0

In [168]:
# 去除掉其中的一列,去掉最后一列
dummy = imdb.content_rating.str.get_dummies().iloc[:,:-1]
dummy

     APPROVED  G  GP  NC-17  NOT RATED  PASSED  PG  PG-13  R  TV-MA  UNRATED
0           0  0   0      0          0       0   0      0  1      0        0
1           0  0   0      0          0       0   0      0  1      0        0
2           0  0   0      0          0       0   0      0  1      0        0
3           0  0   0      0          0       0   0      1  0      0        0
4           0  0   0      0          0       0   0      0  1      0        0
5           0  0   0      0          1       0   0      0  0      0        0
6           0  0   0      0          1       0   0      0  0      0        0
7           0  0   0      0          0       0   0      1  0      0        0
8           0  0   0      0          0       0   0      0  1      0        0
9           0  0   0      0          0       0   0      0  1      0        0
10          0  0   0      0          0       0   0      1  0      0        0
11          0  0   0      0          0       0   0      1  0      0        0
12          0  0   0      0          0       0   1      0  0      0        0
13          0  0   0      0          0       0   0      1  0      0        0
14          0  0   0      0          0       0   0      1  0      0        0
15          0  0   0      0          0       0   0      1  0      0        0
16          0  0   0      0          0       0   0      0  1      0        0
17          0  0   0      0          0       0   0      0  0      0        1
18          0  0   0      0          0       0   0      0  1      0        0
19          0  0   0      0          0       0   1      0  0      0        0
20          0  0   0      0          0       0   0      0  1      0        0
21          0  0   0      0          0       0   0      0  1      0        0
22          1  0   0      0          0       0   0      0  0      0        0
23          0  0   0      0          0       0   0      0  1      0        0
24          0  0   0      0          0       0   0      0  1      0        0
25          0  0   0      0          0       0   0      1  0      0        0
26          0  0   0      0          0       0   0      1  0      0        0
27          0  0   0      0          0       0   0      0  1      0        0
28          0  0   0      0          0       0   0      0  1      0        0
29          0  0   0      0          0       1   0      0  0      0        0
..        ... ..  ..    ...        ...     ...  ..    ... ..    ...      ...
949         0  0   0      0          0       0   1      0  0      0        0
950         0  0   0      0          0       0   0      0  1      0        0
951         0  0   0      0          0       0   0      0  1      0        0
952         0  0   0      0          0       0   0      0  1      0        0
953         0  0   0      0          0       0   1      0  0      0        0
954         0  0   0      0          0       0   0      1  0      0        0
955         0  0   0      0          0       0   0      0  1      0        0
956         0  0   0      0          0       0   1      0  0      0        0
957         0  0   0      0          0       0   0      0  1      0        0
958         0  0   0      0          0       0   0      1  0      0        0
959         0  0   0      0          0       0   0      0  1      0        0
960         0  0   0      0          0       0   0      1  0      0        0
961         0  0   0      0          0       0   0      0  1      0        0
962         0  0   0      0          0       0   1      0  0      0        0
963         0  0   0      0          0       0   0      0  1      0        0
964         0  0   0      0          0       0   0      1  0      0        0
965         0  0   0      0          0       0   0      1  0      0        0
966         0  0   0      0          0       0   0      1  0      0        0
967         0  0   0      0          0       0   0      0  1      0        0
968         0  0   0      0          0       0   0      0  1      0        0
969         0  0   0      0          0       0   0      0  1      0        0
970         0  0   0      0          0       0   0      0  1      0        0
971         0  0   0      0          0       0   0      0  1      0        0
972         0  0   0      1          0       0   0      0  0      0        0
973         0  0   0      0          0       0   0      1  0      0        0
974         0  0   0      0          0       0   1      0  0      0        0
975         0  0   0      0          0       0   1      0  0      0        0
976         0  0   0      0          0       0   0      1  0      0        0
977         0  0   0      0          0       0   1      0  0      0        0
978         0  0   0      0          0       0   0      0  1      0        0

[979 rows x 11 columns]

In [170]:
# 删除原列
imdb.pop('content_rating')

0              R
1              R
2              R
3          PG-13
4              R
5      NOT RATED
6      NOT RATED
7          PG-13
8              R
9              R
10         PG-13
11         PG-13
12            PG
13         PG-13
14         PG-13
15         PG-13
16             R
17       UNRATED
18             R
19            PG
20             R
21             R
22      APPROVED
23             R
24             R
25         PG-13
26         PG-13
27             R
28             R
29        PASSED
         ...
949           PG
950            R
951            R
952            R
953           PG
954        PG-13
955            R
956           PG
957            R
958        PG-13
959            R
960        PG-13
961            R
962           PG
963            R
964        PG-13
965        PG-13
966        PG-13
967            R
968            R
969            R
970            R
971            R
972        NC-17
973        PG-13
974           PG
975           PG
976        PG-13
977           PG
978            R
Name: content_rating, Length: 979, dtype: object

In [173]:
# 拼接哑变量之后的列数据
imdb_dummy = pd.concat([imdb,dummy],axis=1)
imdb_dummy

,star_rating,title,genre,duration,actors_list,APPROVED,G,GP,NC-17,NOT RATED,PASSED,PG,PG-13,R,TV-MA,UNRATED
0,9.3,The Shawshank Redemption,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",0,0,0,0,0,0,0,0,1,0,0
1,9.2,The Godfather,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",0,0,0,0,0,0,0,0,1,0,0
2,9.1,The Godfather: Part II,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",0,0,0,0,0,0,0,0,1,0,0
3,9.0,The Dark Knight,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E...",0,0,0,0,0,0,0,1,0,0,0
4,8.9,Pulp Fiction,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L....",0,0,0,0,0,0,0,0,1,0,0
5,8.9,12 Angry Men,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...",0,0,0,0,1,0,0,0,0,0,0
6,8.9,"The Good, the Bad and the Ugly",Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...",0,0,0,0,1,0,0,0,0,0,0
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...",0,0,0,0,0,0,0,1,0,0,0
8,8.9,Schindler's List,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...",0,0,0,0,0,0,0,0,1,0,0
9,8.9,Fight Club,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh...",0,0,0,0,0,0,0,0,1,0,0
10,8.8,The Lord of the Rings: The Fellowship of the Ring,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl...",0,0,0,0,0,0,0,1,0,0,0
11,8.8,Inception,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...",0,0,0,0,0,0,0,1,0,0,0
12,8.8,Star Wars: Episode V - The Empire Strikes Back,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...",0,0,0,0,0,0,1,0,0,0,0
13,8.8,Forrest Gump,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']",0,0,0,0,0,0,0,1,0,0,0
14,8.8,The Lord of the Rings: The Two Towers,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort...",0,0,0,0,0,0,0,1,0,0,0
15,8.7,Interstellar,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J...",0,0,0,0,0,0,0,1,0,0,0
16,8.7,One Flew Over the Cuckoo's Nest,Drama,133,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich...",0,0,0,0,0,0,0,0,1,0,0
17,8.7,Seven Samurai,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...",0,0,0,0,0,0,0,0,0,0,1
18,8.7,Goodfellas,Biography,146,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']",0,0,0,0,0,0,0,0,1,0,0
19,8.7,Star Wars,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...",0,0,0,0,0,0,1,0,0,0,0
20,8.7,The Matrix,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car...",0,0,0,0,0,0,0,0,1,0,0
21,8.7,City of God,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael...",0,0,0,0,0,0,0,0,1,0,0
22,8.7,It's a Wonderful Life,Drama,130,"[u'James Stewart', u'Donna Reed', u'Lionel Bar...",1,0,0,0,0,0,0,0,0,0,0
23,8.7,The Usual Suspects,Crime,106,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa...",0,0,0,0,0,0,0,0,1,0,0
24,8.7,Se7en,Drama,127,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac...",0,0,0,0,0,0,0,0,1,0,0
25,8.6,Life Is Beautiful,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G...",0,0,0,0,0,0,0,1,0,0,0
26,8.6,Once Upon a Time in the West,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia...",0,0,0,0,0,0,0,1,0,0,0
27,8.6,The Silence of the Lambs,Drama,118,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren...",0,0,0,0,0,0,0,0,1,0,0
28,8.6,Leon: The Professional,Crime,110,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm...",0,0,0,0,0,0,0,0,1,0,0
29,8.6,City Lights,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F...",0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,7.4,Home Alone,Comedy,103,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St...",0,0,0,0,0,0,1,0,0,0,0
950,7.4,Bound,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan...",0,0,0,0,0,0,0,0,1,0,0
951,7.4,Sleepy Hollow,Drama,105,"[u'Johnny Depp', u'Christina Ricci', u'Miranda...",0,0,0,0,0,0,0,0,1,0,0
952,7.4,Pirate Radio,Comedy,117,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N...",0,0,0,0,0,0,0,0,1,0,0
953,7.4,The NeverEnding Story,Adventure,102,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St...",0,0,0,0,0,0,1,0,0,0,0
954,7.4,X-Men,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc...",0,0,0,0,0,0,0,1,0,0,0
955,7.4,Zero Dark Thirty,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri...",0,0,0,0,0,0,0,0,1,0,0
956,7.4,Manhattan Murder Mystery,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']",0,0,0,0,0,0,1,0,0,0,0
957,7.4,National Lampoon's Vacation,Comedy,98,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Imogen...",0,0,0,0,0,0,0,0,1,0,0
958,7.4,My Sister's Keeper,Drama,109,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B...",0,0,0,0,0,0,0,1,0,0,0
959,7.4,Deconstructing Harry,Comedy,96,"[u'Woody Allen', u'Judy Davis', u'Julia Louis-...",0,0,0,0,0,0,0,0,1,0,0
960,7.4,The Way Way Back,Comedy,103,"[u'Steve Carell', u'Toni Collette', u'Allison ...",0,0,0,0,0,0,0,1,0,0,0
961,7.4,Capote,Biography,114,"[u'Philip Seymour Hoffman', u'Clifton Collins ...",0,0,0,0,0,0,0,0,1,0,0
962,7.4,Driving Miss Daisy,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay...",0,0,0,0,0,0,1,0,0,0,0
963,7.4,La Femme Nikita,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F...",0,0,0,0,0,0,0,0,1,0,0
964,7.4,Lincoln,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ...",0,0,0,0,0,0,0,1,0,0,0
965,7.4,Limitless,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor...",0,0,0,0,0,0,0,1,0,0,0
966,7.4,The Simpsons Movie,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy...",0,0,0,0,0,0,0,1,0,0,0
967,7.4,The Rock,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']",0,0,0,0,0,0,0,0,1,0,0
968,7.4,The English Patient,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will...",0,0,0,0,0,0,0,0,1,0,0
969,7.4,Law Abiding Citizen,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']",0,0,0,0,0,0,0,0,1,0,0
970,7.4,Wonder Boys,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc...",0,0,0,0,0,0,0,0,1,0,0
971,7.4,Death at a Funeral,Comedy,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew...",0,0,0,0,0,0,0,0,1,0,0
972,7.4,Blue Valentine,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John...",0,0,0,1,0,0,0,0,0,0,0
973,7.4,The Cider House Rules,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha...",0,0,0,0,0,0,0,1,0,0,0
974,7.4,Tootsie,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G...",0,0,0,0,0,0,1,0,0,0,0
975,7.4,Back to the Future Part III,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma...",0,0,0,0,0,0,1,0,0,0,0
976,7.4,Master and Commander: The Far Side of the World,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo...",0,0,0,0,0,0,0,1,0,0,0
977,7.4,Poltergeist,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr...",0,0,0,0,0,0,1,0,0,0,0
978,7.4,Wall Street,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar...",0,0,0,0,0,0,0,0,1,0,0