In [16]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [23]:
#单个excel表格式为xlsx，可以读取100+万行
import openpyxl
filename="C:\\Users\\有福有德\\Desktop\\上海统计分析python20191216\\data\\短期绩效.xlsx"
inwb=openpyxl.load_workbook(filename)

gsheet=inwb.get_sheet_names()
sname=inwb.get_sheet_by_name(gsheet[0])

dataset=[]
for r in range(1,sname.max_row+1):#range(1,102)
    col=[]
    for c in range(1,sname.max_column+1):#识别最大列，但好像有bage，因此+1
        col.append(sname.cell(r,c).value)
    dataset.append(col)
dataset[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  import sys

[['ID', '员工编号', '性别', '部门', '绩效总分', '适应总分', '情绪总分'],
 [1, 1, 1, 1, 12, 11, 12],
 [2, 2, 1, 3, 13, 10, 12],
 [3, 3, 1, 1, 20, 10, 14],
 [4, 4, 2, 2, 8, 12, 8]]

In [10]:
#使用pandas读取数据支持xls和xlsx
data=pd.read_excel("C:\\Users\\有福有德\\Desktop\\上海统计分析python20191216\\data\\短期绩效.xlsx")
#data.iloc[:,[0,3,4,5]]
#data.tail(6)#显示数据最后6行
data.head(6)#显示数据开头6行

   ID  员工编号  性别  部门  绩效总分  适应总分  情绪总分
0   1     1   1   1    12    11    12
1   2     2   1   3    13    10    12
2   3     3   1   1    20    10    14
3   4     4   2   2     8    12     8
4   5     5   2   3    11    12    12
5   6     6   2   1    11    11    10

In [12]:
#定义sheet读取表格中间的数据
data=pd.read_excel("C:\\Users\\有福有德\\Desktop\\上海统计分析python20191216\\data\\短期绩效.xlsx",
                   sheet_name="b2",
                   header=5,
                   usecols="f:l",
                   )
data.head(6).tail(3)

# header=17,#header=None即没有变量名，header=3即第4行做变量名
# sheet_name=1,#sheet_name=“sheet5”
# names=("var1","var2","var3","var4","var5","var6","var7"),#指定变量名
# usecols="e:k",#control columus scope:"c,e:g",显示c和从e到g
# usecols=5,一共5列
# nrows=6#一共多少行参与分析
# skipfooter=8 #最后尾部8行不读取
# skiprows=22   #开始22行不读取
# converters={"绩效总分":str}#文件的"绩效总分"列读取为str对象类型

   ID  员工编号  性别  部门  绩效总分  适应总分  情绪总分
3   4     4   2   2     8    12     8
4   5     5   2   3    11    12    12
5   6     6   2   1    11    11    10

In [15]:
#读入多张excel表
with pd.ExcelFile("C:\\Users\\有福有德\\Desktop\\上海统计分析python20190407\\data\\短期绩效.xlsx") as xls:
    df1=pd.read_excel(xls,"a1")
    df2=pd.read_excel(xls,"b2")
    df3=pd.read_excel(xls,"c3")
df1.head(6)

   ID  员工编号  性别  部门  绩效总分  适应总分  情绪总分
0   1     1   1   1    12    11    12
1   2     2   1   3    13    10    12
2   3     3   1   1    20    10    14
3   4     4   2   2     8    12     8
4   5     5   2   3    11    12    12
5   6     6   2   1    11    11    10